name: Overflow
main: me.jumba.overflow.Overflow
version: 3.10
description: Overflow Anti-Cheat
commands:
     overflow:
       usage: /<command>
       description: Overflow Anti-Cheat's Main Command
